export enum CinematicStage {
IDEA='IDEA',
SCRIPT='SCRIPT',
STORYBOARD='STORYBOARD',
SHOTS='SHOTS',
CHARACTERS='CHARACTERS',
WORLD='WORLD',
VOICE='VOICE',
MUSIC='MUSIC',
VIDEO='VIDEO',
EDIT='EDIT',
RENDER='RENDER',
DELIVERY='DELIVERY'
}
