export enum StudioEvent {
PROJECT_CREATED='PROJECT_CREATED',
SCRIPT_CREATED='SCRIPT_CREATED',
STORYBOARD_CREATED='STORYBOARD_CREATED',
SHOT_PLAN_CREATED='SHOT_PLAN_CREATED',
RENDER_STARTED='RENDER_STARTED',
RENDER_COMPLETED='RENDER_COMPLETED'
}
