"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SystemOrchestrator = void 0;
const agent_registry_1 = require("./agent_registry");
const executor_agent_1 = require("./executor_agent");
const observer_agent_1 = require("./observer_agent");
const strategist_agent_1 = require("./strategist_agent");
const security_agent_1 = require("./security_agent");
const distribution_agent_1 = require("./distribution_agent");
const predictive_agent_v2_1 = require("./predictive_agent_v2");
const healing_agent_1 = require("./healing_agent");
const integrity_agent_1 = require("./integrity_agent");
const sync_agent_1 = require("./sync_agent");
const audit_agent_1 = require("./audit_agent");
const network_agent_1 = require("./network_agent");
const cache_agent_1 = require("./cache_agent");
const event_bus_agent_1 = require("./event_bus_agent");
const resource_agent_1 = require("./resource_agent");
const gateway_agent_1 = require("./gateway_agent");
const config_agent_1 = require("./config_agent");
const health_agent_1 = require("./health_agent");
const deploy_agent_1 = require("./deploy_agent");
const datalake_agent_1 = require("./datalake_agent");
const intelligence_agent_1 = require("./intelligence_agent");
const simulation_agent_1 = require("./simulation_agent");
const dashboard_agent_1 = require("./dashboard_agent");
const compliance_agent_1 = require("./compliance_agent");
const autoscaling_agent_1 = require("./autoscaling_agent");
const exception_agent_1 = require("./exception_agent");
const encryption_agent_1 = require("./encryption_agent");
const scheduler_agent_1 = require("./scheduler_agent");
const shared_memory_agent_1 = require("./shared_memory_agent");
const ids_agent_1 = require("./ids_agent");
const eco_agent_1 = require("./eco_agent");
const protocol_agent_1 = require("./protocol_agent");
const assistant_agent_1 = require("./assistant_agent");
const federated_learning_agent_1 = require("./federated_learning_agent");
const risk_management_agent_1 = require("./risk_management_agent");
const perf_monitor_agent_1 = require("./perf_monitor_agent");
const innovation_agent_1 = require("./innovation_agent");
const state_manager_1 = require("./state_manager");
class SystemOrchestrator {
    registry = new agent_registry_1.AgentRegistry();
    state = new state_manager_1.StateManager();
    constructor(kernel) {
        this.registry.register(new executor_agent_1.ExecutorAgent('EXEC_01', kernel));
        this.registry.register(new observer_agent_1.ObserverAgent('OBS_01'));
        this.registry.register(new strategist_agent_1.StrategistAgent('STRAT_01'));
        this.registry.register(new security_agent_1.SecurityAgent('SEC_01'));
        this.registry.register(new distribution_agent_1.DistributionAgent('DIST_01'));
        this.registry.register(new predictive_agent_v2_1.PredictiveAgentV2('PRED_V2_01'));
        this.registry.register(new healing_agent_1.HealingAgent('HEAL_01'));
        this.registry.register(new integrity_agent_1.IntegrityAgent('INT_01'));
        this.registry.register(new sync_agent_1.SyncAgent('SYNC_01'));
        this.registry.register(new audit_agent_1.AuditAgent('AUDIT_01'));
        this.registry.register(new network_agent_1.NetworkAgent('NET_01'));
        this.registry.register(new cache_agent_1.CacheAgent('CACHE_01'));
        this.registry.register(new event_bus_agent_1.EventBusAgent('BUS_01'));
        this.registry.register(new resource_agent_1.ResourceAgent('RES_01'));
        this.registry.register(new gateway_agent_1.GatewayAgent('GATE_01'));
        this.registry.register(new config_agent_1.ConfigAgent('CFG_01'));
        this.registry.register(new health_agent_1.HealthAgent('HLTH_01'));
        this.registry.register(new deploy_agent_1.DeployAgent('DEPL_01'));
        this.registry.register(new datalake_agent_1.DataLakeAgent('DL_01'));
        this.registry.register(new intelligence_agent_1.IntelligenceAgent('INTEL_01'));
        this.registry.register(new simulation_agent_1.SimulationAgent('SIM_01'));
        this.registry.register(new dashboard_agent_1.DashboardAgent('DASH_01'));
        this.registry.register(new compliance_agent_1.ComplianceAgent('COMP_01'));
        this.registry.register(new autoscaling_agent_1.AutoScalingAgent('SCALE_01'));
        this.registry.register(new exception_agent_1.ExceptionAgent('EXC_01'));
        this.registry.register(new encryption_agent_1.EncryptionAgent('CRYPT_01'));
        this.registry.register(new scheduler_agent_1.SchedulerAgent('SCHED_01'));
        this.registry.register(new shared_memory_agent_1.SharedMemoryAgent('MEM_01'));
        this.registry.register(new ids_agent_1.IDSAgent('IDS_01'));
        this.registry.register(new eco_agent_1.EcoAgent('ECO_01'));
        this.registry.register(new protocol_agent_1.ProtocolAgent('PROTO_01'));
        this.registry.register(new assistant_agent_1.AssistantAgent('ASST_01'));
        this.registry.register(new federated_learning_agent_1.FederatedLearningAgent('FED_01'));
        this.registry.register(new risk_management_agent_1.RiskManagementAgent('RISK_01'));
        this.registry.register(new perf_monitor_agent_1.PerfMonitorAgent('PERF_01'));
        this.registry.register(new innovation_agent_1.InnovationAgent('INNO_01'));
    }
}
exports.SystemOrchestrator = SystemOrchestrator;
