import { AgentRegistry } from './agent_registry';
import { ExecutorAgent } from './executor_agent';
import { ObserverAgent } from './observer_agent';
import { StrategistAgent } from './strategist_agent';
import { SecurityAgent } from './security_agent';
import { DistributionAgent } from './distribution_agent';
import { PredictiveAgentV2 } from './predictive_agent_v2';
import { HealingAgent } from './healing_agent';
import { IntegrityAgent } from './integrity_agent';
import { SyncAgent } from './sync_agent';
import { AuditAgent } from './audit_agent';
import { NetworkAgent } from './network_agent';
import { CacheAgent } from './cache_agent';
import { EventBusAgent } from './event_bus_agent';
import { ResourceAgent } from './resource_agent';
import { GatewayAgent } from './gateway_agent';
import { ConfigAgent } from './config_agent';
import { HealthAgent } from './health_agent';
import { DeployAgent } from './deploy_agent';
import { DataLakeAgent } from './datalake_agent';
import { IntelligenceAgent } from './intelligence_agent';
import { SimulationAgent } from './simulation_agent';
import { DashboardAgent } from './dashboard_agent';
import { ComplianceAgent } from './compliance_agent';
import { AutoScalingAgent } from './autoscaling_agent';
import { ExceptionAgent } from './exception_agent';
import { EncryptionAgent } from './encryption_agent';
import { SchedulerAgent } from './scheduler_agent';
import { SharedMemoryAgent } from './shared_memory_agent';
import { IDSAgent } from './ids_agent';
import { EcoAgent } from './eco_agent';
import { ProtocolAgent } from './protocol_agent';
import { AssistantAgent } from './assistant_agent';
import { FederatedLearningAgent } from './federated_learning_agent';
import { RiskManagementAgent } from './risk_management_agent';
import { PerfMonitorAgent } from './perf_monitor_agent';
import { InnovationAgent } from './innovation_agent';
import { StateManager } from './state_manager';
import { StorageKernelV2 } from '../storage/kernel_v2/storage_kernel_v2';

export class SystemOrchestrator {
    public registry = new AgentRegistry();
    public state = new StateManager();

    constructor(kernel: StorageKernelV2) {
        this.registry.register(new ExecutorAgent('EXEC_01', kernel));
        this.registry.register(new ObserverAgent('OBS_01'));
        this.registry.register(new StrategistAgent('STRAT_01'));
        this.registry.register(new SecurityAgent('SEC_01'));
        this.registry.register(new DistributionAgent('DIST_01'));
        this.registry.register(new PredictiveAgentV2('PRED_V2_01'));
        this.registry.register(new HealingAgent('HEAL_01'));
        this.registry.register(new IntegrityAgent('INT_01'));
        this.registry.register(new SyncAgent('SYNC_01'));
        this.registry.register(new AuditAgent('AUDIT_01'));
        this.registry.register(new NetworkAgent('NET_01'));
        this.registry.register(new CacheAgent('CACHE_01'));
        this.registry.register(new EventBusAgent('BUS_01'));
        this.registry.register(new ResourceAgent('RES_01'));
        this.registry.register(new GatewayAgent('GATE_01'));
        this.registry.register(new ConfigAgent('CFG_01'));
        this.registry.register(new HealthAgent('HLTH_01'));
        this.registry.register(new DeployAgent('DEPL_01'));
        this.registry.register(new DataLakeAgent('DL_01'));
        this.registry.register(new IntelligenceAgent('INTEL_01'));
        this.registry.register(new SimulationAgent('SIM_01'));
        this.registry.register(new DashboardAgent('DASH_01'));
        this.registry.register(new ComplianceAgent('COMP_01'));
        this.registry.register(new AutoScalingAgent('SCALE_01'));
        this.registry.register(new ExceptionAgent('EXC_01'));
        this.registry.register(new EncryptionAgent('CRYPT_01'));
        this.registry.register(new SchedulerAgent('SCHED_01'));
        this.registry.register(new SharedMemoryAgent('MEM_01'));
        this.registry.register(new IDSAgent('IDS_01'));
        this.registry.register(new EcoAgent('ECO_01'));
        this.registry.register(new ProtocolAgent('PROTO_01'));
        this.registry.register(new AssistantAgent('ASST_01'));
        this.registry.register(new FederatedLearningAgent('FED_01'));
        this.registry.register(new RiskManagementAgent('RISK_01'));
        this.registry.register(new PerfMonitorAgent('PERF_01'));
        this.registry.register(new InnovationAgent('INNO_01'));
    }
}
